package com.bytedance.sdk.openadsdk.fc;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.wu;
import com.bytedance.sdk.openadsdk.core.dkl.aq;
import com.bytedance.sdk.openadsdk.core.dkl.dkl;
import com.bytedance.sdk.openadsdk.core.dkl.dse;
import com.bytedance.sdk.openadsdk.utils.dnm;
import com.bytedance.sdk.openadsdk.utils.jip;
import com.bytedance.sdk.openadsdk.utils.sq;

/* JADX INFO: compiled from: r8-map-id-1868b3f846f91b929d17a1f0de6da199bc8101b6e9bb94a36f131322636ef84b */
/* JADX INFO: loaded from: classes.dex */
public class qor extends dse {
    public qor(Context context) {
        this(context, null);
    }

    private void hnj(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        dse dseVar = new dse(context);
        dseVar.setId(jip.hw);
        dseVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        dseVar.setBackgroundColor(0);
        dseVar.setGravity(17);
        addView(dseVar);
        View gjvVar = new com.bytedance.sdk.openadsdk.core.dkl.gjv(context);
        gjvVar.setId(jip.f14674qi);
        gjvVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        dseVar.addView(gjvVar);
        dkl dklVar = new dkl(context);
        dklVar.setId(jip.f14669mn);
        int iHn = sq.hn(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iHn, iHn);
        layoutParams.addRule(13);
        dklVar.setLayoutParams(layoutParams);
        dklVar.setIndeterminateDrawable(dnm.hnj(context, "tt_video_loading_progress_bar"));
        dseVar.addView(dklVar);
        com.bytedance.sdk.openadsdk.core.dkl.sk skVar = new com.bytedance.sdk.openadsdk.core.dkl.sk(context);
        skVar.setId(jip.f14692xe);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        skVar.setLayoutParams(layoutParams2);
        skVar.setGravity(1);
        skVar.setOrientation(1);
        skVar.setVisibility(8);
        dseVar.addView(skVar);
        com.bytedance.sdk.openadsdk.core.dkl.gjv gjvVar2 = new com.bytedance.sdk.openadsdk.core.dkl.gjv(context);
        gjvVar2.setId(jip.lx);
        gjvVar2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        gjvVar2.setImageDrawable(dnm.hnj(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        gjvVar2.setScaleType(scaleType);
        skVar.addView(gjvVar2);
        aq aqVar = new aq(context);
        aqVar.setId(jip.f14678sh);
        aqVar.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        aqVar.setText(wu.hnj(context, "tt_video_retry_des_txt"));
        aqVar.setTextColor(Color.parseColor("#999999"));
        skVar.addView(aqVar);
        com.bytedance.sdk.openadsdk.core.dkl.gjv gjvVar3 = new com.bytedance.sdk.openadsdk.core.dkl.gjv(context);
        gjvVar3.setId(jip.tq);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        gjvVar3.setLayoutParams(layoutParams3);
        gjvVar3.setScaleType(scaleType);
        gjvVar3.setImageDrawable(dnm.hnj(context, "tt_play_movebar_textpage"));
        gjvVar3.setVisibility(8);
        addView(gjvVar3);
        com.bytedance.sdk.openadsdk.core.dkl.gjv gjvVar4 = new com.bytedance.sdk.openadsdk.core.dkl.gjv(context);
        gjvVar4.setId(jip.f14680sl);
        int iHn2 = sq.hn(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(iHn2, iHn2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iHn3 = sq.hn(context, 7.0f);
        layoutParams4.setMarginEnd(iHn3);
        layoutParams4.rightMargin = iHn3;
        layoutParams4.topMargin = iHn3;
        gjvVar4.setLayoutParams(layoutParams4);
        gjvVar4.setBackground(dnm.hnj(context, "tt_detail_video_btn_bg"));
        gjvVar4.setScaleType(scaleType);
        gjvVar4.setImageDrawable(dnm.hnj(context, "tt_close_move_detail"));
        addView(gjvVar4);
        aq aqVar2 = new aq(context);
        aqVar2.setId(jip.f14691xd);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        aqVar2.setLayoutParams(layoutParams5);
        aqVar2.setBackground(dnm.hnj(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        aqVar2.setEllipsize(truncateAt);
        aqVar2.setMaxLines(2);
        int iHn4 = sq.hn(context, 15.0f);
        aqVar2.setPadding(iHn4, sq.hn(context, 14.0f), iHn4, 0);
        aqVar2.setSingleLine(false);
        aqVar2.setTextColor(-1);
        aqVar2.setTextSize(2, 17.0f);
        aqVar2.setVisibility(8);
        addView(aqVar2);
        dse dseVar2 = new dse(context);
        dseVar2.setId(jip.f14683tb);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        dseVar2.setLayoutParams(layoutParams6);
        dseVar2.setBackground(dnm.hnj(context, "tt_video_black_desc_gradient"));
        dseVar2.setGravity(16);
        dseVar2.setVisibility(8);
        addView(dseVar2);
        com.bytedance.sdk.openadsdk.core.dkl.gjv gjvVar5 = new com.bytedance.sdk.openadsdk.core.dkl.gjv(context);
        int i10 = jip.kby;
        gjvVar5.setId(i10);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iHn5 = sq.hn(context, 12.0f);
        layoutParams7.leftMargin = iHn5;
        layoutParams7.setMarginStart(iHn5);
        gjvVar5.setLayoutParams(layoutParams7);
        gjvVar5.setScaleType(scaleType);
        gjvVar5.setImageDrawable(dnm.hnj(context, "tt_leftbackbutton_titlebar_photo_preview"));
        dseVar2.addView(gjvVar5);
        aq aqVar3 = new aq(context);
        aqVar3.setId(jip.br);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iHn6 = sq.hn(context, 16.0f);
        layoutParams8.leftMargin = iHn6;
        layoutParams8.rightMargin = iHn;
        layoutParams8.setMarginStart(iHn6);
        layoutParams8.setMarginEnd(iHn);
        layoutParams8.addRule(17, i10);
        int i11 = jip.cq;
        layoutParams8.addRule(0, i11);
        layoutParams8.addRule(1, i10);
        layoutParams8.addRule(16, i11);
        aqVar3.setLayoutParams(layoutParams8);
        aqVar3.setEllipsize(truncateAt);
        aqVar3.setGravity(16);
        aqVar3.setMaxLines(1);
        aqVar3.setSingleLine(true);
        aqVar3.setTextColor(-1);
        aqVar3.setTextSize(2, 17.0f);
        dseVar2.addView(aqVar3);
        com.bytedance.sdk.openadsdk.core.dkl.sk skVar2 = new com.bytedance.sdk.openadsdk.core.dkl.sk(context);
        skVar2.setId(i11);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iHn7 = sq.hn(context, 14.0f);
        layoutParams9.rightMargin = iHn7;
        layoutParams9.setMarginEnd(iHn7);
        skVar2.setLayoutParams(layoutParams9);
        skVar2.setGravity(16);
        skVar2.setOrientation(1);
        dseVar2.addView(skVar2);
        aq aqVar4 = new aq(context);
        aqVar4.setId(jip.bqc);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        aqVar4.setLayoutParams(layoutParams10);
        aqVar4.setGravity(16);
        aqVar4.setMaxLines(1);
        aqVar4.setSingleLine(true);
        aqVar4.setTextColor(-1);
        aqVar4.setTextSize(2, 12.0f);
        skVar2.addView(aqVar4);
        com.bytedance.sdk.openadsdk.core.dkl.sk skVar3 = new com.bytedance.sdk.openadsdk.core.dkl.sk(context);
        skVar3.setId(jip.f14681sp);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, sq.hn(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        skVar3.setLayoutParams(layoutParams11);
        skVar3.setGravity(16);
        skVar3.setOrientation(0);
        skVar3.setVisibility(8);
        addView(skVar3);
        aq aqVar5 = new aq(context);
        aqVar5.setId(jip.ett);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iHn6;
        layoutParams12.rightMargin = iHn5;
        layoutParams12.setMarginEnd(iHn5);
        layoutParams12.setMarginStart(iHn6);
        aqVar5.setLayoutParams(layoutParams12);
        aqVar5.setText(wu.hnj(context, "tt_00_00"));
        aqVar5.setTextColor(-1);
        aqVar5.setTextSize(2, 10.0f);
        skVar3.addView(aqVar5);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(jip.cvc);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, sq.hn(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(dnm.hnj(context, "tt_seek_progress"));
        seekBar.setThumb(dnm.hnj(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        skVar3.addView(seekBar);
        aq aqVar6 = new aq(context);
        aqVar6.setId(jip.zyh);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iHn5;
        layoutParams14.rightMargin = iHn6;
        layoutParams14.setMarginEnd(iHn6);
        layoutParams14.setMarginStart(iHn5);
        aqVar6.setLayoutParams(layoutParams14);
        aqVar6.setText(wu.hnj(context, "tt_00_00"));
        aqVar6.setTextColor(-1);
        aqVar6.setTextSize(2, 10.0f);
        skVar3.addView(aqVar6);
        com.bytedance.sdk.openadsdk.core.dkl.gjv gjvVar6 = new com.bytedance.sdk.openadsdk.core.dkl.gjv(context);
        gjvVar6.setId(jip.pdc);
        gjvVar6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        gjvVar6.setPadding(iHn6, 0, iHn6, 0);
        gjvVar6.setScaleType(scaleType);
        gjvVar6.setVisibility(8);
        gjvVar6.setImageDrawable(wu.qor(context, "tt_enlarge_video"));
        skVar3.addView(gjvVar6);
        View hnVar = new hn(context);
        hnVar.setId(jip.f14677sg);
        hnVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(hnVar);
        aq aqVar7 = new aq(context);
        aqVar7.setId(jip.ldn);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iHn5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        aqVar7.setLayoutParams(layoutParams15);
        aqVar7.setBackgroundColor(Color.parseColor("#00000000"));
        aqVar7.setText("close");
        aqVar7.setMinHeight(sq.hn(context, 44.0f));
        aqVar7.setCompoundDrawablesWithIntrinsicBounds(dnm.hnj(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(aqVar7);
    }

    public qor(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public qor(Context context, AttributeSet attributeSet, int i10) {
        super(context, attributeSet, i10);
        hnj(context);
    }
}
