name: Mod APK with Morphe

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: false
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Morphe Desktop
        run: |
          wget -O morphe.jar "https://github.com/MorpheApp/morphe-desktop/releases/download/v1.15.0/morphe-desktop-1.15.0-all.jar"

      - name: Download Morphe patches
        run: |
          wget -O patches.mpp "https://github.com/sjshb57/Pairip-Patches/releases/download/v1.10.3/patches-1.10.3.mpp"

      - name: Help
        run: |
          java -jar morphe.jar list-patches \
          --patches=patches.mpp \
          --with-descriptions \
          --with-packages \
          --with-versions \
          --with-options