name: Android Emulator Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Android
        uses: android-actions/setup-android@v4

      - name: Install Emulator Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse0

      - name: Install Emulator
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager \
            "emulator" \
            "platform-tools" \
            "system-images;android-36;google_apis_playstore;x86_64"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd \
            -n android36 \
            -k "system-images;android-36;google_apis_playstore;x86_64" \
            --force

      - name: Enable KVM
        run: |
          sudo chmod 666 /dev/kvm

      - name: Check Emulator
        run: |
          echo "=== Emulator ==="
          "$ANDROID_HOME/emulator/emulator" -version

          echo "=== ADB ==="
          "$ANDROID_HOME/platform-tools/adb" version

          echo "=== AVD ==="
          avdmanager list avd

          echo "=== System Image ==="
          sdkmanager --list_installed | grep "system-images;android-36"

          echo "=== KVM ==="
          ls -l /dev/kvm || true
          [[ -r /dev/kvm && -w /dev/kvm ]] && echo "KVM: OK" || echo "KVM: NOT AVAILABLE"

      - name: Start Emulator
       
        run: |
          nohup "$ANDROID_HOME/emulator/emulator" \
            -avd android36 \
            -no-window \
            -no-audio \
            -no-snapshot \
            -gpu swiftshader_indirect > emulator.log 2>&1 &

          sleep 20

          echo "=== Emulator log ==="
          cat emulator.log

          echo "=== ADB devices ==="
          "$ANDROID_HOME/platform-tools/adb" devices -l

      - name: Install APK
       
        run: |
          cd azrecorder
          "$ANDROID_HOME/platform-tools/adb" install-multiple \
            -i com.android.vending \
            base.apk \
            *.x86_64.apk \
            *.en.apk \
            *dpi.apk