name: Test 3
on:
  push:
permissions:
  actions: read
  contents: write
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir tmp
          curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" -o tmp/file.zip "https://api.github.com/repos/EclCoder/Test/actions/artifacts/9899830069/zip"
          unzip tmp/file.zip
          unzip tmp/*.apkm

      - name: Extract lib
        run: |
          unzip tmp/*armeabi_v7a.apk "lib/armeabi-v7a/*" -d .
          unzip tmp/*arm64_v8a.apk "lib/arm64-v8a/*" -d .
          rm -rf tmp/

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update files" || exit 0
          git push
        