name: Test 2
on:
  push:
permissions:
  actions: read
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          wget -O file.zip "https://github.com/EclCoder/Test/actions/runs/33771486417/artifacts/9899830069"
          unzip file.zip
          ls
          