name: Test 2
on:
  push:
permissions:
  actions: read
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check tools
        run: |
          which java || true
          which apktool || true
          which jadx || true