name: Decompile APK

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache tools
        uses: actions/cache@v4
        with:
          path: ~/.cache/tools
          key: tools

      - name: Install tools
        run: |
          mkdir -p ~/.cache/tools/
          if [ ! -d ~/.cache/tools/jadx ]; then
            curl -L -o jadx.zip "https://github.com/skylot/jadx/releases/download/v1.5.6/jadx-1.5.6.zip"
            unzip jadx.zip -d ~/.cache/tools
            rm jadx.zip
          fi
          if [ ! -d ~/.cache/tools/apktool.jar ]; then
            curl -L -o ~/.cache/tools/apktool.jar "https://github.com/iBotPeaches/Apktool/releases/download/v3.0.3/apktool_3.0.3.jar"
            
          fi
          