name: Test 3
on:
  push:
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check runner resources
        run: |
          echo "CPU:"
          nproc

          echo "RAM:"
          free -h

          echo "CPU info:"
          lscpu | grep -E 'Model name|CPU\(s\)'